environment: docker
baseUrl: http://localhost:3000 # TODO replace
baseFrontendUrl: http://localhost:4200 // TODO replace

registration:
  mode: disabled # email = registration via email/smtp | disabled = registration via adminpanel

defaultUserSizeLimitGB: -1 # -1 = unlimited

mongodb:
  uri: mongodb://mongodb:27017/captioning

redis:
  host: redis
  port: 6379

jwt:
  secret: YOUR_JWT_SECRET # TODO replace
  issuer: http://localhost:3000 # TODO replace
  audience: http://localhost:4200 # TODO replace

melvinAsr:
  host: http://localhost:8000
  apikey: YOUR_ASR_SECRET # TODO replace

basicAuth:
  username: melvin
  password: YOUR_BASIC_AUTH_SECRET # TODO replace

adminUser:
  username: admin
  # you can either set a cleartext or a hashed password (-> htpasswd -nbB admin secret)
  password: secret
  # hashedPassword: admin:$2y$05$jswg1DsryRkK.NUwFQvxqOTC1VAO/CMOp5f6pJ4IPY5gTzm/zyWbu
#email:
#  smtpServer: "smtp.example.com"
#  smtpPort: 465
#  user: "info@example.com"
#  password: "secret"
#  mailFrom: info@example.com
#  mailFromName: Melvin
